In [1]:
import re
import jieba
import jieba.analyse
import pandas as pd
import numpy as np
from collections import Counter

In [2]:
firstdata = pd.read_csv("final_01.csv")

In [3]:
firstdata.count()

文章日期    29
標題      30
作者      27
新聞內容    30
dtype: int64

In [4]:
print("文章的實際總數為"+str(firstdata["標題"].count())+"篇")

文章的實際總數為30篇

In [5]:
firstdata["titleword"]=""
firstdata["articleword"]=""
firstdata.head

<bound method NDFrame.head of           文章日期                                           標題        作者  \
0     2022/7/5    真實鐵達尼號唯一日本倖存者，回國竟被痛罵懦夫、國恥！死後日記揭「真相」讓世人都沉默       連珮妤
1   2018/11/12  鐵達尼號的真實故事：世界首富把救生船的位子讓給了三等艙的婦女，只為守護「保護弱者」原則       周慧心
2    2022/4/11                  鐵達尼號真人真事　歌女戀富二代天人永隔　生還後終生不嫁       陳婉珺
3   2021年12月7日                      《鐵達尼號》中相擁而逝的老夫婦 真實故事更催淚       張小清
4    2014/4/14                       除了淒美愛情...你該知道的鐵達尼號10件事        阿咖
5    2022/5/13         鐵達尼號真人真事｜窮歌女戀上富二代 甜蜜登船最終天人永隔 遺物揭深情回憶        RD
6     2020/5/1               17位《鐵達尼號》真實人物　「只出現一幕的夫人」才是大英雄！      扒拉文史
7     2020/9/5                           《鐵達尼號》，5個基於真實人物的角色   君君DIARY
8   2021/12/12                         鐵達尼號上的真實故事 — 人性的6個抉擇   英倫是你的情人
9   2021/12/12                             我們所不知道真實的鐵達尼號的故事      李剛看盤
10   2020/8/27                     鐵達尼號：揭祕火遍全球的電影背後悲慘而真實的故事    學地理觀海洋
11  2021/12/12                         鐵達尼號背後的真實故事:你所不知道的柔情      魔力視頻
12    2021/2/7                       「永不沉沒的布朗夫人」|鐵達尼號的真實女主角  TARGET目標
13   2021/4/14                「鐵達尼號」倖存者逃生真相：哭喊聲、槍聲與船轟然倒下的瞬間       蔡娪嫣
14  2019/10/19                  悲慟！鐵達尼號唯一倖存的副船長 公開當年的「沉船真相」      三立新聞
15   2020/7/31               【鐵達尼號】傳奇倖存者三遇海難仍死裡逃生　獲封永不沉沒的女士       王誦賢
16   2019/12/9               【鐵達尼號】紀錄片揭倖存者從未曝光信件　記載撞冰山後救援經歷       王誦賢
17   2017/8/26                   「泰坦尼克」號有6名中國倖存者 背後有段很醜陋的故事        木易
18   2017/7/19                   電影裡都是假的！歷史上鐵達尼號真實故事本沒有那麼美好     歷史小組長
19   2021/9/20                 泰坦尼克號上竟然有8名中國人！他們是誰？他們的命運如何？       馮學榮
20   2019/8/20          泰坦尼克号电影之外的真实故事丨当船开始下沉，你知道人们在呼喊什么吗？          無
21   2022/4/27                比利時婦自稱鐵達尼號生還者 離世後真相曝光竟藏淒美愛情故事         無
22   2017/5/31                       今日係......鐵達尼號最後一名生還者死忌         無
23  2017/12/29                鐵達尼號最後一位倖存者的遺言被世人流傳 重要的「人生課程」         無
24   2021/4/22                               蒙冤百年　鐵達尼六華工獲正名         無
25   2014/5/28                                 一位鐵達尼號生還者的回憶         無
26   2016/3/18                                  鐵達尼號倖存者及其現狀       NaN
27    2006/5/8                               鐵達尼最後生還者　99歲辭世       NaN
28   2017/8/30                       鐵達尼號沉沒逾1500人遇難　最後救起一華人       NaN
29         NaN                           愛永不沉沒 泰坦尼克的巨富們感動後世       周慧心

                                                 新聞內容 titleword articleword
0   20多年來，好萊塢電影《鐵達尼號》（Titanic、泰坦尼克號）中男女主角的動人故事，讓許多...
1   1912年4月14日深夜，「不沉之船」——鐵達尼號（ Titanic）在北大西洋撞上冰山。2...
2   今年是鐵達尼號沉沒110週年，明珠台昨晚（10日）重播由里安納度狄卡比奧（Leonardo ...
3   人類歷史上發生過的天災人禍或許不計其數，但在當代人心中，上世紀初的「鐵達尼號」沉船事件尤其令...
4   講到「發生在大船上的淒美愛情故事」時，相信九成九的人會不假思索說出《鐵達尼號》這個答案，儘管...
5   1912年4月14日，一艘曾號稱永不沉沒的夢幻之船「鐵達尼號」因撞上冰山而沉沒，不少人從此失...
6   相信大家一定都對經典電影《鐵達尼號》的畫面相當熟悉，無論是劇情、對白，甚至主題曲和角色都記得...
7   災難巨片《鐵達尼號》是基於一個真實的故事，但並不是每個角色都是來自真實故事。1912年4月1...
8   106年前的今天，即1912年4月10日，鐵達尼號在英國的南安普頓碼頭鳴笛起航，開始了她第一...
9   100年前的4月，號稱「永不沉沒」的巨輪鐵達尼號開始了它的處女航。4月14日深夜，鐵達尼號撞...
10  鐵達尼號是全球聞名，高成本大製作的一部災難愛情片，講述兩個主角傑克和露絲跨越階層的偉大的愛情...
11  在第一艘救生艇下水後，我對甲板上一名姓斯特勞的女人說道：「你能隨我一起到那隻救生艇上去嗎？」...
12  還記得《鐵達尼號》裡面由奧斯卡影后凱西·貝茨扮演的那個胖婦人嗎？露絲的媽媽輕蔑地稱她是「暴發...
13  1912年4月14日深夜，當時世界上最巨大華美的船艦「鐵達尼號」（RMS Titanic），...
14  大家都知道《鐵達尼號》中傑克和蘿絲的感人愛情故事，但你對鐵達尼號還有更深的認識嗎？它的背後究...
15  由占士金馬倫（James Cameron）執導；里安納度狄卡比奧（Leonardo DiCa...
16  由占士金馬倫（James Cameron）執導；里安納度狄卡比奧（Leonardo DiCa...
17  真實的「泰坦尼克」號海難後，不但有悽美的愛情故事，還藏著醜陋的種族主義歧視。從昨天起，有個事...
18  歷史上泰坦號，船身長達三幢半住宅大廈的長度，曾經被歐美新聞界譽為「海上城市」而且在世界航海史...
19  大家還記得美國電影《泰坦尼克號》嗎？傑克和肉絲的愛情故事。1912年沈沒的那艘客輪泰坦尼克號...
20  1912年4月14日那个恐怖的夜晚，泰坦尼克号上共有705人得救，1502人罹难。泰坦尼克号...
21  浪漫程度不輸虛構的電影情節1997年上映，以「鐵達尼號沉沒事件」為背景的經典電影《鐵達尼號》...
22  從事地圖繪製工作的Millvina Dean雖然只是英國一名公務員，但自從兩個月大時經歷了一...
23  1912年4月14日的鐵達尼號沉船事件，至今已104年。那是鐵達尼號首航，載著超過2200名...
24  1912年4月14日的鐵達尼號沉船事件，至今已104年。那是鐵達尼號首航，載著超過2200名...
25  在1912年4月14日那個恐怖的夜晚，鐵達尼號上共有705人得救，1502人罹難。38歲的查...
26  鐵達尼號倖存者鐵達尼號撞冰山沉沒之後，3點30分，卡納德公司的客船卡帕西亞號最先趕到了出事現...
27  史上最慘痛的船難，鐵達尼號事故，最後一位居住在美國的生還者，阿斯普朗女士，6日在麻州的家中過...
28  「鐵達尼號」是1912年建成的豪華郵輪，同年首航時卻發生沉船意外，造成逾1500人喪生，成為...
29  1912年4月14日深夜，「不沉之船」——泰坦尼克號（也稱鐵達尼號，Titanic）在北大西...                        >

In [6]:
index = 0
for sentence in firstdata["標題"]:#取出表格中標題的內容
    doct_list=jieba.analyse.extract_tags(sentence,200)#挑出200個最重要的單詞
    firstdata["titleword"].iloc[index]=doct_list#將每個字句的重點單詞放在各個項目之中
    index += 1
firstdata["titleword"]

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\paylung\AppData\Local\Temp\jieba.cache
Loading model cost 0.727 seconds.
Prefix dict has been built successfully.

0     [真實, 鐵達尼號, 存者, 回國, 國恥, 死後日記, 懦夫, 真相, 世人, 沉默, 唯...
1     [鐵達尼號, 真實, 讓給, 婦女, 只為, 守護, 保護, 原則, 救生船, 弱者, 首富...
2              [鐵達尼號, 戀富, 天人永隔, 還後終, 生不嫁, 真人真事, 歌女, 二代]
3                       [鐵達尼號, 中相, 擁而逝, 真實, 催淚, 老夫, 故事]
4                         [淒美愛情, ..., 鐵達尼號, 10, 除了, 知道]
5     [鐵達尼號, 戀上富, 最終, 天人永隔, 遺物, 回憶, 真人真事, 登船, 歌女, 二代...
6                    [17, 鐵達尼號, 真實, 出現, 一幕, 英雄, 夫人, 人物]
7                                [鐵達尼號, 個基, 真實, 角色, 人物]
8                                [鐵達尼號, 真實, 抉擇, 人性, 故事]
9                                [我們, 真實, 鐵達尼號, 故事, 知道]
10                  [鐵達尼號, 火遍, 電影, 背後悲, 慘而, 真實, 故事, 全球]
11                               [鐵達尼號, 真實, 柔情, 故事, 知道]
12                          [鐵達尼號, 真實, 女主角, 永不, 布朗, 夫人]
13               [鐵達尼號, 存者, 槍聲, 轟然, 瞬間, 哭喊, 逃生, 真相, 倒下]
14               [悲慟, 鐵達尼號, 倖存, 船長, 公開, 當年, 沉船, 真相, 唯一]
15           [鐵達尼號, 傳奇, 存者, 三遇, 海難, 死裡, 獲封, 逃生, 永不, 女士]
16              [鐵達尼號, 紀錄片, 存者, 記載, 經歷, 冰山, 信件, 曝光, 救援]
17                     [泰坦尼克, 號有, 名中國, 存者, 背後有, 醜陋, 故事]
18                      [電影裡, 歷史, 鐵達尼號, 真實, 那麼, 美好, 故事]
19                      [他們, 泰坦尼克, 號上, 名中國, 命運, 竟然, 如何]
20    [当船, 泰坦尼克号, 下沉, 呼喊, 电影, 真实, 故事, 之外, 人们, 知道, 开始...
21    [時婦, 自稱, 鐵達尼號生, 還者, 離世, 竟藏, 淒美愛情, 比利, 真相, 曝光, 故事]
22                          [......, 鐵達尼號, 生還者, 一名, 今日]
23               [鐵達尼號, 存者, 遺言, 流傳, 課程, 世人, 人生, 一位, 重要]
24                                 [鐵達尼六華工, 蒙冤, 正名, 百年]
25                                  [鐵達尼號生, 還者, 回憶, 一位]
26                                   [鐵達尼號, 存者, 現狀, 及其]
27                               [鐵達尼, 最後生, 還者, 99, 辭世]
28                            [鐵達尼號, 1500, 人遇, 一華人, 救起]
29                             [泰坦尼克, 沉沒, 感動後世, 巨富, 永不]
Name: titleword, dtype: object

In [7]:
seconddata=firstdata[["標題","titleword"]]
seconddata

,標題,titleword
0,真實鐵達尼號唯一日本倖存者，回國竟被痛罵懦夫、國恥！死後日記揭「真相」讓世人都沉默,"[真實, 鐵達尼號, 存者, 回國, 國恥, 死後日記, 懦夫, 真相, 世人, 沉默, 唯..."
1,鐵達尼號的真實故事：世界首富把救生船的位子讓給了三等艙的婦女，只為守護「保護弱者」原則,"[鐵達尼號, 真實, 讓給, 婦女, 只為, 守護, 保護, 原則, 救生船, 弱者, 首富..."
2,鐵達尼號真人真事 歌女戀富二代天人永隔 生還後終生不嫁,"[鐵達尼號, 戀富, 天人永隔, 還後終, 生不嫁, 真人真事, 歌女, 二代]"
3,《鐵達尼號》中相擁而逝的老夫婦 真實故事更催淚,"[鐵達尼號, 中相, 擁而逝, 真實, 催淚, 老夫, 故事]"
4,除了淒美愛情...你該知道的鐵達尼號10件事,"[淒美愛情, ..., 鐵達尼號, 10, 除了, 知道]"
5,鐵達尼號真人真事｜窮歌女戀上富二代 甜蜜登船最終天人永隔 遺物揭深情回憶,"[鐵達尼號, 戀上富, 最終, 天人永隔, 遺物, 回憶, 真人真事, 登船, 歌女, 二代..."
6,17位《鐵達尼號》真實人物 「只出現一幕的夫人」才是大英雄！,"[17, 鐵達尼號, 真實, 出現, 一幕, 英雄, 夫人, 人物]"
7,《鐵達尼號》，5個基於真實人物的角色,"[鐵達尼號, 個基, 真實, 角色, 人物]"
8,鐵達尼號上的真實故事 — 人性的6個抉擇,"[鐵達尼號, 真實, 抉擇, 人性, 故事]"
9,我們所不知道真實的鐵達尼號的故事,"[我們, 真實, 鐵達尼號, 故事, 知道]"
10,鐵達尼號：揭祕火遍全球的電影背後悲慘而真實的故事,"[鐵達尼號, 火遍, 電影, 背後悲, 慘而, 真實, 故事, 全球]"
11,鐵達尼號背後的真實故事:你所不知道的柔情,"[鐵達尼號, 真實, 柔情, 故事, 知道]"
12,「永不沉沒的布朗夫人」|鐵達尼號的真實女主角,"[鐵達尼號, 真實, 女主角, 永不, 布朗, 夫人]"
13,「鐵達尼號」倖存者逃生真相：哭喊聲、槍聲與船轟然倒下的瞬間,"[鐵達尼號, 存者, 槍聲, 轟然, 瞬間, 哭喊, 逃生, 真相, 倒下]"
14,悲慟！鐵達尼號唯一倖存的副船長 公開當年的「沉船真相」,"[悲慟, 鐵達尼號, 倖存, 船長, 公開, 當年, 沉船, 真相, 唯一]"
15,【鐵達尼號】傳奇倖存者三遇海難仍死裡逃生 獲封永不沉沒的女士,"[鐵達尼號, 傳奇, 存者, 三遇, 海難, 死裡, 獲封, 逃生, 永不, 女士]"
16,【鐵達尼號】紀錄片揭倖存者從未曝光信件 記載撞冰山後救援經歷,"[鐵達尼號, 紀錄片, 存者, 記載, 經歷, 冰山, 信件, 曝光, 救援]"
17,「泰坦尼克」號有6名中國倖存者 背後有段很醜陋的故事,"[泰坦尼克, 號有, 名中國, 存者, 背後有, 醜陋, 故事]"
18,電影裡都是假的！歷史上鐵達尼號真實故事本沒有那麼美好,"[電影裡, 歷史, 鐵達尼號, 真實, 那麼, 美好, 故事]"
19,泰坦尼克號上竟然有8名中國人！他們是誰？他們的命運如何？,"[他們, 泰坦尼克, 號上, 名中國, 命運, 竟然, 如何]"
20,泰坦尼克号电影之外的真实故事丨当船开始下沉，你知道人们在呼喊什么吗？,"[当船, 泰坦尼克号, 下沉, 呼喊, 电影, 真实, 故事, 之外, 人们, 知道, 开始..."
21,比利時婦自稱鐵達尼號生還者 離世後真相曝光竟藏淒美愛情故事,"[時婦, 自稱, 鐵達尼號生, 還者, 離世, 竟藏, 淒美愛情, 比利, 真相, 曝光, 故事]"
22,今日係......鐵達尼號最後一名生還者死忌,"[......, 鐵達尼號, 生還者, 一名, 今日]"
23,鐵達尼號最後一位倖存者的遺言被世人流傳 重要的「人生課程」,"[鐵達尼號, 存者, 遺言, 流傳, 課程, 世人, 人生, 一位, 重要]"
24,蒙冤百年 鐵達尼六華工獲正名,"[鐵達尼六華工, 蒙冤, 正名, 百年]"
25,一位鐵達尼號生還者的回憶,"[鐵達尼號生, 還者, 回憶, 一位]"
26,鐵達尼號倖存者及其現狀,"[鐵達尼號, 存者, 現狀, 及其]"
27,鐵達尼最後生還者 99歲辭世,"[鐵達尼, 最後生, 還者, 99, 辭世]"
28,鐵達尼號沉沒逾1500人遇難 最後救起一華人,"[鐵達尼號, 1500, 人遇, 一華人, 救起]"
29,愛永不沉沒 泰坦尼克的巨富們感動後世,"[泰坦尼克, 沉沒, 感動後世, 巨富, 永不]"

In [8]:
seconddata.to_csv("final_02.csv",index=False) #將現有的資料存檔

In [23]:
jieba.load_userdict("final01_useword.txt") #將字補完整
jieba.analyse.set_stop_words("final01_noword.txt") #去除不重要的字，要放在同個資料夾
index = 0
for sentence in seconddata["標題"]:#取出表格中的內容
    doct_list=jieba.analyse.extract_tags(sentence,200)#挑出200個最重要的單詞
    seconddata["titleword"].iloc[index]=doct_list#將每個字句的重點單詞放在各個項目之中
    index += 1
seconddata["titleword"]

C:\Users\paylung\AppData\Local\Temp\ipykernel_12272\1077754952.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seconddata["titleword"].iloc[index]=doct_list#將每個字句的重點單詞放在各個項目之中

0       [鐵達尼號, 倖存者, 回國, 國恥, 死後日記, 懦夫, 真相, 世人, 沉默, 日本]
1     [鐵達尼號, 婦女, 守護, 保護, 原則, 救生船, 弱者, 首富, 三等, 位子, 故事]
2               [鐵達尼號, 富二代, 天人永隔, 生還, 終生不嫁, 真人真事, 歌女]
3                         [鐵達尼號, 中相, 擁而逝, 催淚, 老夫, 故事]
4                                        [淒美愛情, 鐵達尼號]
5     [鐵達尼號, 富二代, 天人永隔, 遺物, 回憶, 真人真事, 登船, 歌女, 甜蜜, 深情]
6                              [鐵達尼號, 出現, 英雄, 夫人, 人物]
7                                      [鐵達尼號, 角色, 人物]
8                                  [鐵達尼號, 抉擇, 人性, 故事]
9                                          [鐵達尼號, 故事]
10                             [鐵達尼號, 火遍, 電影, 故事, 全球]
11                                     [鐵達尼號, 柔情, 故事]
12                                  [布朗夫人, 鐵達尼號, 女主角]
13                        [鐵達尼號, 倖存者, 槍聲, 哭喊, 逃生, 真相]
14                     [悲慟, 鐵達尼號, 倖存, 船長, 公開, 沉船, 真相]
15                        [鐵達尼號, 傳奇, 倖存者, 海難, 逃生, 女士]
16           [鐵達尼號, 紀錄片, 倖存者, 記載, 經歷, 冰山, 信件, 曝光, 救援]
17                            [泰坦尼克, 中國, 倖存者, 醜陋, 故事]
18                        [電影裡, 歷史, 鐵達尼號, 那麼, 美好, 故事]
19                             [他們, 泰坦尼克, 號上, 中國, 命運]
20                        [泰坦尼克号, 下沉, 呼喊, 电影, 真实, 故事]
21            [比利時婦, 自稱, 鐵達尼號生還者, 離世, 真相曝光, 淒美愛情, 故事]
22                                [......, 鐵達尼號, 生還者]
23                  [鐵達尼號, 倖存者, 遺言, 流傳, 人生課程, 世人, 重要]
24                               [鐵達尼六華工, 蒙冤, 正名, 百年]
25                                      [鐵達尼號生還者, 回憶]
26                                    [鐵達尼號, 倖存者, 現狀]
27                                   [鐵達尼, 最後生還者, 辭世]
28                                [鐵達尼號, 遇難, 一華人, 救起]
29                               [泰坦尼克, 沉沒, 感動後世, 巨富]
Name: titleword, dtype: object

In [24]:
seconddata_list=seconddata['titleword'].tolist()
type(seconddata_list)

list

In [25]:
flat=[x for sublist in seconddata_list for x in sublist]#將所有清單進行整併
diction=Counter(flat)

In [26]:
diction_key=pd.DataFrame(diction.keys())
diction_value=pd.DataFrame(diction.values())
df=[diction_key,diction_value]
result=pd.concat(df,axis=1)#增加第一列
result.columns=["標題關鍵字","次數"]
result

    標題關鍵字  次數
0    鐵達尼號  22
1     倖存者   7
2      回國   1
3      國恥   1
4    死後日記   1
..    ...  ..
102   一華人   1
103    救起   1
104    沉沒   1
105  感動後世   1
106    巨富   1

[107 rows x 2 columns]

In [27]:
bigger3 = result[(result["次數"]>2)].sort_values(by=["次數"])#做排序的方式
bigger3

   標題關鍵字  次數
6     真相   3
67  泰坦尼克   3
1    倖存者   7
19    故事  10
0   鐵達尼號  22

In [28]:
result["標題關鍵字"]

0      鐵達尼號
1       倖存者
2        回國
3        國恥
4      死後日記
       ...
102     一華人
103      救起
104      沉沒
105    感動後世
106      巨富
Name: 標題關鍵字, Length: 107, dtype: object

In [29]:
type(result["標題關鍵字"].iloc[0])

str

In [30]:
result01_keyword=result["標題關鍵字"].tolist()
type(result01_keyword)

list

In [34]:
result01_keyword

['鐵達尼號',
 '倖存者',
 '回國',
 '國恥',
 '死後日記',
 '懦夫',
 '真相',
 '世人',
 '沉默',
 '日本',
 '婦女',
 '守護',
 '保護',
 '原則',
 '救生船',
 '弱者',
 '首富',
 '三等',
 '位子',
 '故事',
 '富二代',
 '天人永隔',
 '生還',
 '終生不嫁',
 '真人真事',
 '歌女',
 '中相',
 '擁而逝',
 '催淚',
 '老夫',
 '淒美愛情',
 '遺物',
 '回憶',
 '登船',
 '甜蜜',
 '深情',
 '出現',
 '英雄',
 '夫人',
 '人物',
 '角色',
 '抉擇',
 '人性',
 '火遍',
 '電影',
 '全球',
 '柔情',
 '布朗夫人',
 '女主角',
 '槍聲',
 '哭喊',
 '逃生',
 '悲慟',
 '倖存',
 '船長',
 '公開',
 '沉船',
 '傳奇',
 '海難',
 '女士',
 '紀錄片',
 '記載',
 '經歷',
 '冰山',
 '信件',
 '曝光',
 '救援',
 '泰坦尼克',
 '中國',
 '醜陋',
 '電影裡',
 '歷史',
 '那麼',
 '美好',
 '他們',
 '號上',
 '命運',
 '泰坦尼克号',
 '下沉',
 '呼喊',
 '电影',
 '真实',
 '比利時婦',
 '自稱',
 '鐵達尼號生還者',
 '離世',
 '真相曝光',
 '......',
 '生還者',
 '遺言',
 '流傳',
 '人生課程',
 '重要',
 '鐵達尼六華工',
 '蒙冤',
 '正名',
 '百年',
 '現狀',
 '鐵達尼',
 '最後生還者',
 '辭世',
 '遇難',
 '一華人',
 '救起',
 '沉沒',
 '感動後世',
 '巨富']

In [40]:
result01_keyword.remove('......')
result01_keyword

['鐵達尼號',
 '倖存者',
 '回國',
 '國恥',
 '死後日記',
 '懦夫',
 '真相',
 '世人',
 '沉默',
 '日本',
 '婦女',
 '守護',
 '保護',
 '原則',
 '救生船',
 '弱者',
 '首富',
 '三等',
 '位子',
 '故事',
 '富二代',
 '天人永隔',
 '生還',
 '終生不嫁',
 '真人真事',
 '歌女',
 '中相',
 '擁而逝',
 '催淚',
 '老夫',
 '淒美愛情',
 '遺物',
 '回憶',
 '登船',
 '甜蜜',
 '深情',
 '出現',
 '英雄',
 '夫人',
 '人物',
 '角色',
 '抉擇',
 '人性',
 '火遍',
 '電影',
 '全球',
 '柔情',
 '布朗夫人',
 '女主角',
 '槍聲',
 '哭喊',
 '逃生',
 '悲慟',
 '倖存',
 '船長',
 '公開',
 '沉船',
 '傳奇',
 '海難',
 '女士',
 '紀錄片',
 '記載',
 '經歷',
 '冰山',
 '信件',
 '曝光',
 '救援',
 '泰坦尼克',
 '中國',
 '醜陋',
 '電影裡',
 '歷史',
 '那麼',
 '美好',
 '他們',
 '號上',
 '命運',
 '泰坦尼克号',
 '下沉',
 '呼喊',
 '电影',
 '真实',
 '比利時婦',
 '自稱',
 '鐵達尼號生還者',
 '離世',
 '真相曝光',
 '生還者',
 '遺言',
 '流傳',
 '人生課程',
 '重要',
 '鐵達尼六華工',
 '蒙冤',
 '正名',
 '百年',
 '現狀',
 '鐵達尼',
 '最後生還者',
 '辭世',
 '遇難',
 '一華人',
 '救起',
 '沉沒',
 '感動後世',
 '巨富']